#!/bin/sh
if [ ! -e dwm/config.h ]; then
  ./patch
fi
echo "Installing..."
cd dwm && sudo make clean install
cd ../session
yes n | sudo cp dwm-personalized.desktop /usr/share/xsessions
yes n | sudo cp dwm-personalized /usr/bin
