#!/bin/sh
if [ ! -e dwm/config.h ]; then
  ./patch
fi
echo "Installing..."
cd dwm && sudo make clean install
cd ../session

if [ ! -e /usr/share/xsessions/dwm-personalized.desktop ]; then
  sudo cp dwm-personalized.desktop /usr/share/xsessions
fi

if [ ! -e /usr/bin/dwm-personalized ]; then
  sudo cp dwm-personalized /usr/bin
fi
